import type {
  AggregateType,
  FoundationState,
  LineageLink,
} from "../../foundation/types.js";

import type {
  Fingerprint,
} from "../../domain/primitives.js";

import type {
  JsonValue,
} from "../shared.js";

/**
 * NEXMOLD V8 Intelligence Foundation
 *
 * This module defines the canonical contracts for the
 * intelligence layer.
 *
 * IMPORTANT:
 * - It does NOT replace FoundationRecord.
 * - It does NOT replace FoundationStore.
 * - It does NOT redefine Observation.
 * - It does NOT create a second fingerprint system.
 * - Intelligence objects may reference Foundation lineage,
 *   but may never impersonate Evidence, Claim, Knowledge,
 *   or Decision records.
 *
 * Architectural boundary:
 *
 * Foundation:
 *   Source → Snapshot → Evidence → Claim → Knowledge
 *                         ↓
 *                      Decision
 *
 * Intelligence:
 *   Entity → Signal → Metric → Analysis → Decision Intent
 *                                      ↓
 *                                  Experiment
 *                                      ↓
 *                                   Outcome
 *                                      ↓
 *                                  Learning
 *                                      ↓
 *                                  Feedback
 *                                      ↓
 *                                    Cycle
 *
 * The Intelligence layer consumes Truth-layer provenance.
 * It never manufactures Truth-layer authority.
 */

/* -------------------------------------------------------------------------- */
/* Primitive contracts                                                        */
/* -------------------------------------------------------------------------- */

export type IntelligenceId = string;

export type IntelligenceConfidence =
  | "VERY_LOW"
  | "LOW"
  | "MEDIUM"
  | "HIGH"
  | "VERY_HIGH";

export type IntelligenceLifecycle =
  | "DISCOVERED"
  | "OBSERVED"
  | "ANALYZED"
  | "VALIDATED"
  | "PROPOSED"
  | "APPROVED"
  | "ACTIVE"
  | "MEASURED"
  | "LEARNED"
  | "WATCH"
  | "REJECTED"
  | "RETIRED";

export type IntelligenceStatus =
  | "ACTIVE"
  | "WATCH"
  | "BLOCKED"
  | "REJECTED"
  | "RETIRED";

export type IntelligenceDirection =
  | "POSITIVE"
  | "NEGATIVE"
  | "NEUTRAL"
  | "UNKNOWN";

export type IntelligencePolarity =
  | "OPPORTUNITY"
  | "RISK"
  | "NEUTRAL"
  | "UNKNOWN";

/* -------------------------------------------------------------------------- */
/* Entity                                                                     */
/* -------------------------------------------------------------------------- */

export type IntelligenceEntityType =
  | "INDUSTRY"
  | "MARKET"
  | "COMPANY"
  | "BRAND"
  | "PRODUCT"
  | "SERVICE"
  | "PROCESS"
  | "MATERIAL"
  | "TECHNOLOGY"
  | "TOPIC"
  | "KEYWORD"
  | "QUERY"
  | "PAGE"
  | "CONTENT"
  | "PERSON"
  | "ORGANIZATION"
  | "LOCATION"
  | "PROBLEM"
  | "SOLUTION"
  | "COMPETITOR"
  | "SEARCH_ENGINE"
  | "AI_SYSTEM"
  | "OTHER";

export type EntityRelationshipType =
  | "IS_A"
  | "PART_OF"
  | "RELATED_TO"
  | "ALTERNATIVE_TO"
  | "COMPETES_WITH"
  | "SERVES"
  | "TARGETS"
  | "DEPENDS_ON"
  | "REQUIRES"
  | "SOLVES"
  | "CAUSES"
  | "IMPACTS"
  | "SUPPORTS"
  | "CONTRADICTS"
  | "MENTIONS"
  | "CITES"
  | "RANKS_FOR"
  | "PUBLISHED_AS"
  | "DERIVED_FROM"
  | "UNKNOWN";

export interface IntelligenceEntityAttribute {
  readonly name: string;
  readonly value: JsonValue;
  readonly confidence: IntelligenceConfidence;
  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];
}

export interface IntelligenceEntityRelationship {
  readonly relationshipId: IntelligenceId;
  readonly fromEntityId: IntelligenceId;
  readonly toEntityId: IntelligenceId;
  readonly type: EntityRelationshipType;
  readonly confidence: IntelligenceConfidence;
  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];
  readonly metadata?: Readonly<Record<string, JsonValue>>;
}

export interface IntelligenceEntity {
  readonly entityId: IntelligenceId;
  readonly type: IntelligenceEntityType;

  /**
   * Human-readable canonical name.
   */
  readonly name: string;

  /**
   * Deterministic normalized identity key.
   *
   * This is an identity key, not a Truth-layer fingerprint.
   */
  readonly normalizedName: string;

  /**
   * Deterministic identity fingerprint generated by the
   * intelligence entity implementation.
   */
  readonly identityFingerprint: Fingerprint;

  readonly aliases: readonly string[];

  readonly attributes: readonly IntelligenceEntityAttribute[];

  readonly relationships: readonly IntelligenceEntityRelationship[];

  readonly confidence: IntelligenceConfidence;

  readonly lifecycle: IntelligenceLifecycle;

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly metadata?: Readonly<Record<string, JsonValue>>;

  readonly createdAt: string;
  readonly updatedAt: string;
}

/* -------------------------------------------------------------------------- */
/* Truth-layer provenance                                                     */
/* -------------------------------------------------------------------------- */

/**
 * A reference into the canonical V8 Foundation / Truth layer.
 *
 * This is intentionally a reference, never an embedded replacement for
 * FoundationRecord.
 */
export interface IntelligenceLineageRef {
  readonly aggregateType: AggregateType;
  readonly aggregateId: string;
  readonly version: number;
  readonly fingerprint: Fingerprint;
}

export interface IntelligenceEvidenceRef {
  readonly evidenceId: string;
  readonly sourceId?: string;
  readonly snapshotId?: string;
  readonly aggregateType?: "EVIDENCE" | "OBSERVATION";
  readonly fingerprint?: Fingerprint;
  readonly locator?: string;
  readonly excerpt?: string;
  readonly confidence?: IntelligenceConfidence;
}

/**
 * General provenance container for Intelligence objects.
 */
export interface IntelligenceProvenance {
  readonly lineage: readonly IntelligenceLineageRef[];

  /**
   * Evidence references are intentionally separate from lineage.
   *
   * lineage = immutable Foundation aggregate references
   * evidenceRefs = semantic evidence pointers used by Intelligence
   */
  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  /**
   * Optional parent intelligence object.
   */
  readonly parentIds?: readonly IntelligenceId[];

  /**
   * Deterministic explanation of how this object was produced.
   */
  readonly derivation?: string;
}

/* -------------------------------------------------------------------------- */
/* Signal                                                                     */
/* -------------------------------------------------------------------------- */

export type IntelligenceSignalType =
  | "MARKET"
  | "SEARCH"
  | "SEO"
  | "GEO"
  | "ENTITY"
  | "TOPIC"
  | "COMPETITOR"
  | "CONTENT"
  | "LINK"
  | "TRAFFIC"
  | "ENGAGEMENT"
  | "INQUIRY"
  | "LEAD"
  | "CONVERSION"
  | "REVENUE"
  | "TREND"
  | "TECHNICAL"
  | "SYSTEM"
  | "EXPERIMENT"
  | "LEARNING";

export type IntelligenceSignalSource =
  | "INTERNET"
  | "FOUNDATION"
  | "SEARCH"
  | "SERP"
  | "AI_ANSWER"
  | "ANALYTICS"
  | "CRM"
  | "CMS"
  | "COMPETITOR"
  | "EXPERIMENT"
  | "INTERNAL"
  | "DERIVED";

export interface IntelligenceSignal {
  readonly signalId: IntelligenceId;

  readonly type: IntelligenceSignalType;

  readonly source: IntelligenceSignalSource;

  /**
   * Subject is intentionally a stable semantic reference, not free-form
   * opaque text only.
   */
  readonly subject: string;

  readonly normalizedSubject: string;

  readonly entityIds: readonly IntelligenceId[];

  readonly observedAt: string;

  readonly value: JsonValue;

  readonly unit?: string;

  readonly direction: IntelligenceDirection;

  readonly polarity: IntelligencePolarity;

  readonly confidence: IntelligenceConfidence;

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly metadata?: Readonly<Record<string, JsonValue>>;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Observation                                                                */
/* -------------------------------------------------------------------------- */

/**
 * Foundation already owns OBSERVATION as a canonical aggregate type.
 *
 * This interface describes the Intelligence-facing normalized view.
 * It deliberately does not introduce a second Foundation aggregate.
 */
export interface IntelligenceObservation {
  readonly observationId: IntelligenceId;

  readonly signalId: IntelligenceId;

  readonly subject: string;

  readonly value: JsonValue;

  readonly observedAt: string;

  readonly unit?: string;

  readonly context?: Readonly<Record<string, JsonValue>>;

  readonly sourceId?: string;

  readonly foundationObservationId?: string;

  readonly foundationLineage?: IntelligenceLineageRef;

  readonly confidence: IntelligenceConfidence;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Metric                                                                     */
/* -------------------------------------------------------------------------- */

export type IntelligenceMetricType =
  | "DEMAND"
  | "GROWTH"
  | "COMPETITION"
  | "CONTENT_GAP"
  | "COMMERCIAL_INTENT"
  | "CAPABILITY_FIT"
  | "CONVERSION_POTENTIAL"
  | "EVIDENCE_CONFIDENCE"
  | "TRAFFIC_POTENTIAL"
  | "AUTHORITY"
  | "TOPICAL_COVERAGE"
  | "ENTITY_COVERAGE"
  | "SERP_VISIBILITY"
  | "AI_VISIBILITY"
  | "AI_CITATION_RATE"
  | "AI_MENTION_RATE"
  | "AI_RECOMMENDATION_RATE"
  | "CLICK_THROUGH_RATE"
  | "ENGAGEMENT"
  | "INQUIRY_RATE"
  | "LEAD_RATE"
  | "CONVERSION_RATE"
  | "REVENUE"
  | "CUSTOM";

export interface IntelligenceMetric {
  readonly metricId: IntelligenceId;

  readonly type: IntelligenceMetricType;

  readonly name: string;

  readonly subject: string;

  readonly entityIds: readonly IntelligenceId[];

  readonly value: number;

  readonly normalizedValue: number;

  readonly unit?: string;

  readonly observedAt: string;

  readonly baseline?: number;

  readonly target?: number;

  readonly direction: IntelligenceDirection;

  readonly confidence: IntelligenceConfidence;

  readonly signalIds: readonly IntelligenceId[];

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly metadata?: Readonly<Record<string, JsonValue>>;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Analysis                                                                   */
/* -------------------------------------------------------------------------- */

export type IntelligenceAnalysisType =
  | "CORRELATION"
  | "TREND"
  | "CLUSTER"
  | "GAP"
  | "ANOMALY"
  | "OPPORTUNITY"
  | "RISK"
  | "COMPETITOR"
  | "INTENT"
  | "CANNIBALIZATION"
  | "AUTHORITY"
  | "VISIBILITY"
  | "CONVERSION"
  | "EXPERIMENT"
  | "CUSTOM";

export interface IntelligenceAnalysis {
  readonly analysisId: IntelligenceId;

  readonly type: IntelligenceAnalysisType;

  readonly subject: string;

  readonly signalIds: readonly IntelligenceId[];

  readonly observationIds: readonly IntelligenceId[];

  readonly metricIds: readonly IntelligenceId[];

  readonly finding: string;

  readonly score?: number;

  readonly confidence: IntelligenceConfidence;

  readonly direction: IntelligenceDirection;

  readonly polarity: IntelligencePolarity;

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Decision                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Intelligence decisions are strategic recommendations.
 *
 * They are NOT Foundation DECISION records.
 *
 * A strategic decision that must become an authoritative V8 Truth-layer
 * decision must subsequently enter the canonical Problem → Knowledge →
 * Decision → DecisionValidator pipeline.
 */
export type IntelligenceDecisionType =
  | "APPROVE"
  | "REJECT"
  | "WATCH"
  | "PURSUE"
  | "UPDATE"
  | "MERGE"
  | "SPLIT"
  | "RETIRE"
  | "EXPERIMENT";

export interface IntelligenceDecision {
  readonly decisionId: IntelligenceId;

  readonly type: IntelligenceDecisionType;

  readonly subject: string;

  readonly status: IntelligenceStatus;

  readonly reasons: readonly string[];

  readonly analysisIds: readonly IntelligenceId[];

  readonly signalIds: readonly IntelligenceId[];

  readonly metricIds: readonly IntelligenceId[];

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly confidence: IntelligenceConfidence;

  readonly expectedOutcome?: string;

  readonly constraints: readonly string[];

  /**
   * If this intelligence decision is promoted into the canonical V8
   * Decision pipeline, this field identifies that Foundation decision.
   */
  readonly foundationDecisionId?: string;

  readonly decidedAt: string;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Experiment                                                                 */
/* -------------------------------------------------------------------------- */

export type IntelligenceExperimentStatus =
  | "DRAFT"
  | "PLANNED"
  | "RUNNING"
  | "COMPLETED"
  | "STOPPED"
  | "INVALID"
  | "RETIRED";

export interface IntelligenceExperimentVariant {
  readonly variantId: IntelligenceId;

  readonly name: string;

  readonly description: string;

  readonly parameters: Readonly<Record<string, JsonValue>>;

  readonly fingerprint: Fingerprint;
}

export interface IntelligenceExperiment {
  readonly experimentId: IntelligenceId;

  readonly name: string;

  readonly hypothesis: string;

  readonly status: IntelligenceExperimentStatus;

  readonly subject: string;

  readonly metricIds: readonly IntelligenceId[];

  readonly signalIds: readonly IntelligenceId[];

  readonly variants: readonly IntelligenceExperimentVariant[];

  readonly controlVariantId?: IntelligenceId;

  readonly successCriteria: readonly string[];

  readonly constraints: readonly string[];

  readonly startAt?: string;

  readonly endAt?: string;

  readonly observations: readonly IntelligenceId[];

  readonly outcomeIds: readonly IntelligenceId[];

  readonly confidence: IntelligenceConfidence;

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Outcome                                                                    */
/* -------------------------------------------------------------------------- */

export interface IntelligenceOutcome {
  readonly outcomeId: IntelligenceId;

  readonly experimentId?: IntelligenceId;

  readonly subject: string;

  readonly success: boolean;

  readonly summary: string;

  readonly metricIds: readonly IntelligenceId[];

  readonly observationIds: readonly IntelligenceId[];

  readonly before?: Readonly<Record<string, number>>;

  readonly after?: Readonly<Record<string, number>>;

  readonly delta?: Readonly<Record<string, number>>;

  readonly confidence: IntelligenceConfidence;

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly observedAt: string;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Learning                                                                   */
/* -------------------------------------------------------------------------- */

export type IntelligenceLearningType =
  | "PATTERN"
  | "RULE"
  | "HEURISTIC"
  | "CAUSAL_HINT"
  | "FAILURE"
  | "SUCCESS"
  | "PREFERENCE"
  | "ANOMALY"
  | "STRATEGY";

export type IntelligenceLearningStatus =
  | "CANDIDATE"
  | "VALIDATED"
  | "PROMOTED"
  | "WATCH"
  | "REJECTED"
  | "RETIRED";

export interface IntelligenceLearning {
  readonly learningId: IntelligenceId;

  readonly type: IntelligenceLearningType;

  readonly status: IntelligenceLearningStatus;

  readonly statement: string;

  readonly normalizedStatement: string;

  readonly sourceSignalIds: readonly IntelligenceId[];

  readonly sourceObservationIds: readonly IntelligenceId[];

  readonly sourceExperimentIds: readonly IntelligenceId[];

  readonly sourceOutcomeIds: readonly IntelligenceId[];

  readonly supportingMetricIds: readonly IntelligenceId[];

  readonly confidence: IntelligenceConfidence;

  readonly relevance: number;

  /**
   * Learning decay is represented explicitly so stale patterns cannot
   * silently remain authoritative forever.
   */
  readonly decayRate: number;

  readonly createdAt: string;

  readonly lastValidatedAt?: string;

  readonly expiresAt?: string;

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Feedback                                                                   */
/* -------------------------------------------------------------------------- */

export type IntelligenceFeedbackType =
  | "SEARCH"
  | "SEO"
  | "GEO"
  | "TRAFFIC"
  | "ENGAGEMENT"
  | "INQUIRY"
  | "LEAD"
  | "CONVERSION"
  | "REVENUE"
  | "CONTENT"
  | "EXPERIMENT"
  | "SYSTEM";

export interface IntelligenceFeedback {
  readonly feedbackId: IntelligenceId;

  readonly type: IntelligenceFeedbackType;

  readonly subject: string;

  readonly value: JsonValue;

  readonly observedAt: string;

  readonly entityIds: readonly IntelligenceId[];

  readonly signalIds: readonly IntelligenceId[];

  readonly metricIds: readonly IntelligenceId[];

  readonly outcomeId?: IntelligenceId;

  readonly direction: IntelligenceDirection;

  readonly confidence: IntelligenceConfidence;

  readonly evidenceRefs: readonly IntelligenceEvidenceRef[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly metadata?: Readonly<Record<string, JsonValue>>;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Cycle                                                                      */
/* -------------------------------------------------------------------------- */

export type IntelligenceCycleStage =
  | "DISCOVER"
  | "ANALYZE"
  | "VALIDATE"
  | "DECIDE"
  | "ACT"
  | "MEASURE"
  | "LEARN";

export type IntelligenceCycleStatus =
  | "INITIALIZED"
  | "RUNNING"
  | "BLOCKED"
  | "COMPLETED"
  | "FAILED"
  | "RETIRED";

export interface IntelligenceCycle {
  readonly cycleId: IntelligenceId;

  readonly sequence: number;

  readonly stage: IntelligenceCycleStage;

  readonly status: IntelligenceCycleStatus;

  readonly startedAt: string;

  readonly completedAt?: string;

  readonly parentCycleId?: IntelligenceId;

  readonly entityIds: readonly IntelligenceId[];

  readonly signalIds: readonly IntelligenceId[];

  readonly observationIds: readonly IntelligenceId[];

  readonly metricIds: readonly IntelligenceId[];

  readonly analysisIds: readonly IntelligenceId[];

  readonly decisionIds: readonly IntelligenceId[];

  readonly experimentIds: readonly IntelligenceId[];

  readonly outcomeIds: readonly IntelligenceId[];

  readonly learningIds: readonly IntelligenceId[];

  readonly feedbackIds: readonly IntelligenceId[];

  readonly lineage: readonly IntelligenceLineageRef[];

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Engine input/output                                                        */
/* -------------------------------------------------------------------------- */

export interface IntelligenceFoundationInput {
  readonly cycleId?: string;

  readonly entities?: readonly IntelligenceEntity[];

  readonly signals?: readonly IntelligenceSignal[];

  readonly observations?: readonly IntelligenceObservation[];

  readonly metrics?: readonly IntelligenceMetric[];

  readonly analyses?: readonly IntelligenceAnalysis[];

  readonly decisions?: readonly IntelligenceDecision[];

  readonly experiments?: readonly IntelligenceExperiment[];

  readonly outcomes?: readonly IntelligenceOutcome[];

  readonly learnings?: readonly IntelligenceLearning[];

  readonly feedback?: readonly IntelligenceFeedback[];

  readonly cycles?: readonly IntelligenceCycle[];

  readonly now?: string;

  readonly metadata?: Readonly<Record<string, JsonValue>>;
}

export interface IntelligenceFoundationResult {
  readonly cycle: IntelligenceCycle;

  readonly entities: readonly IntelligenceEntity[];

  readonly signals: readonly IntelligenceSignal[];

  readonly observations: readonly IntelligenceObservation[];

  readonly metrics: readonly IntelligenceMetric[];

  readonly analyses: readonly IntelligenceAnalysis[];

  readonly decisions: readonly IntelligenceDecision[];

  readonly experiments: readonly IntelligenceExperiment[];

  readonly outcomes: readonly IntelligenceOutcome[];

  readonly learnings: readonly IntelligenceLearning[];

  readonly feedback: readonly IntelligenceFeedback[];

  readonly blocked: readonly IntelligenceBlock[];

  readonly fingerprint: Fingerprint;
}

export interface IntelligenceBlock {
  readonly code:
    | "INVALID_INPUT"
    | "MISSING_LINEAGE"
    | "MISSING_EVIDENCE"
    | "INVALID_CONFIDENCE"
    | "INVALID_FINGERPRINT"
    | "DUPLICATE_ID"
    | "ORPHAN_REFERENCE"
    | "CYCLE_INVALID"
    | "DECISION_NOT_SUPPORTED"
    | "EXPERIMENT_INVALID"
    | "LEARNING_NOT_SUPPORTED"
    | "UNKNOWN";

  readonly objectType: string;

  readonly objectId: string;

  readonly message: string;

  readonly lineage: readonly IntelligenceLineageRef[];
}

/* -------------------------------------------------------------------------- */
/* Invariant report                                                           */
/* -------------------------------------------------------------------------- */

export interface IntelligenceInvariantReport {
  readonly valid: boolean;

  readonly checks: readonly string[];

  readonly failures: readonly IntelligenceInvariantFailure[];

  readonly fingerprint: Fingerprint;
}

export interface IntelligenceInvariantFailure {
  readonly code:
    | "MISSING_REQUIRED_FIELD"
    | "INVALID_REFERENCE"
    | "INVALID_LINEAGE"
    | "INVALID_FINGERPRINT"
    | "DUPLICATE_ID"
    | "ORPHAN_OBJECT"
    | "INVALID_STATE"
    | "INVALID_CONFIDENCE"
    | "INVALID_VALUE"
    | "CYCLE_BROKEN"
    | "UNKNOWN";

  readonly objectType: string;

  readonly objectId: string;

  readonly message: string;

  readonly lineage: readonly IntelligenceLineageRef[];
}

/* -------------------------------------------------------------------------- */
/* Canonical object union                                                     */
/* -------------------------------------------------------------------------- */

export type IntelligenceObject =
  | IntelligenceEntity
  | IntelligenceSignal
  | IntelligenceObservation
  | IntelligenceMetric
  | IntelligenceAnalysis
  | IntelligenceDecision
  | IntelligenceExperiment
  | IntelligenceOutcome
  | IntelligenceLearning
  | IntelligenceFeedback
  | IntelligenceCycle;

/* -------------------------------------------------------------------------- */
/* Foundation bridge contracts                                                */
/* -------------------------------------------------------------------------- */

/**
 * A typed bridge used when Intelligence needs to reference an immutable
 * Foundation record without copying or mutating that record.
 *
 * This deliberately accepts only Foundation aggregate records through
 * their structural contract.
 */
export interface IntelligenceFoundationRecordRef {
  readonly aggregateType: AggregateType;

  readonly aggregateId: string;

  readonly version: number;

  readonly state: FoundationState;

  readonly fingerprint: Fingerprint;

  readonly lineage: readonly LineageLink[];
}

/**
 * Foundation references that are allowed to provide authoritative support
 * to Intelligence objects.
 */
export type IntelligenceTruthAggregateType =
  | "SOURCE"
  | "SNAPSHOT"
  | "EVIDENCE"
  | "OBSERVATION"
  | "CLAIM"
  | "KNOWLEDGE"
  | "RULE"
  | "POLICY"
  | "ELIGIBILITY"
  | "SCOPE"
  | "CONTEXT"
  | "PROBLEM"
  | "DECISION"
  | "VERIFICATION";

/**
 * Restricts Intelligence provenance to known Truth/Foundation aggregates.
 */
export interface IntelligenceTruthReference {
  readonly aggregateType: IntelligenceTruthAggregateType;

  readonly aggregateId: string;

  readonly version: number;

  readonly fingerprint: Fingerprint;
}

/* -------------------------------------------------------------------------- */
/* Type guards                                                                */
/* -------------------------------------------------------------------------- */

export function isIntelligenceEntity(
  value: IntelligenceObject,
): value is IntelligenceEntity {
  return (
    "entityId" in value &&
    "identityFingerprint" in value
  );
}

export function isIntelligenceSignal(
  value: IntelligenceObject,
): value is IntelligenceSignal {
  return (
    "signalId" in value &&
    "signal" in value
      ? true
      : "signalId" in value &&
        "observedAt" in value &&
        "fingerprint" in value
  );
}

export function isIntelligenceMetric(
  value: IntelligenceObject,
): value is IntelligenceMetric {
  return (
    "metricId" in value &&
    "normalizedValue" in value &&
    "value" in value
  );
}

export function isIntelligenceDecision(
  value: IntelligenceObject,
): value is IntelligenceDecision {
  return (
    "decisionId" in value &&
    "decidedAt" in value &&
    "reasons" in value
  );
}

export function isIntelligenceExperiment(
  value: IntelligenceObject,
): value is IntelligenceExperiment {
  return (
    "experimentId" in value &&
    "hypothesis" in value &&
    "variants" in value
  );
}

export function isIntelligenceLearning(
  value: IntelligenceObject,
): value is IntelligenceLearning {
  return (
    "learningId" in value &&
    "statement" in value &&
    "decayRate" in value
  );
}

export function isIntelligenceFeedback(
  value: IntelligenceObject,
): value is IntelligenceFeedback {
  return (
    "feedbackId" in value &&
    "observedAt" in value &&
    "direction" in value
  );
}

export function isIntelligenceCycle(
  value: IntelligenceObject,
): value is IntelligenceCycle {
  return (
    "cycleId" in value &&
    "sequence" in value &&
    "stage" in value &&
    "status" in value
  );
}