import test from "node:test";
import assert from "node:assert/strict";
import { createMarketDemand } from "../../../../.v8-build/src/v8/intelligence/market/demand.js";
import { evaluateMarketDecision } from "../../../../.v8-build/src/v8/intelligence/market/decision-engine.js";
import { compileMarketResearchPlan } from "../../../../.v8-build/src/v8/intelligence/market/research-strategy.js";
import { assessCoverage } from "../../../../.v8-build/src/v8/intelligence/market/coverage-intelligence.js";
import { detectEvidenceConflicts } from "../../../../.v8-build/src/v8/intelligence/market/conflict-intelligence.js";
import { detectCannibalization } from "../../../../.v8-build/src/v8/intelligence/market/cannibalization-intelligence.js";
import { InMemoryMarketMemory } from "../../../../.v8-build/src/v8/intelligence/market/market-memory.js";
function demand(){return createMarketDemand({id:"market-demand:fullchain:001",market:"US",geography:"United States",language:"en",audience:"B2B product engineers",problem:"How to determine injection molding wall thickness",intent:"INFORMATIONAL",entities:["injection molding","wall thickness"],queryObservations:[{id:"observation:fullchain:001",query:"injection molding wall thickness",normalizedQuery:"injection molding wall thickness",source:"SEARCH",intent:"INFORMATIONAL",language:"en",market:"US",observedAt:"2026-09-23T00:00:00.000Z"}],demandSignals:[{type:"PROBLEM_SIGNAL",value:"wall thickness guidance",sourceObservationIds:["observation:fullchain:001"]}],existingCoverage:[],uncertainty:"LOW"});}
test("full market chain plans research without bypassing truth",()=>{const d=demand();const r=evaluateMarketDecision({decisionId:"market-decision:fullchain:001",demand:d,evidence:{availableEvidence:[],missingEvidence:["material-specific guidance"],contradictions:[],unresolvedQuestions:[]},coverage:{existingCoverageRefs:[],equivalentCoverage:[],relatedCoverage:[]}});assert.equal(r.decision.state,"RESEARCH_REQUIRED");const plan=compileMarketResearchPlan(d,r.researchActions);assert.ok(plan.queries.length>0);});
test("coverage analysis detects equivalent coverage",()=>{const d=demand();const c=assessCoverage(d,[{ref:"article:wall",query:"injection molding wall thickness",problem:d.problem,entities:d.entities}]);assert.equal(c.relation,"EQUIVALENT");});
test("conflict intelligence is fail-closed",()=>{const c=detectEvidenceConflicts([{evidenceId:"e1",subject:"wall thickness",predicate:"recommended",value:"1mm"},{evidenceId:"e2",subject:"wall thickness",predicate:"recommended",value:"3mm"}]);assert.equal(c.clean,false);assert.equal(c.conflicts.length,1);});
test("cannibalization detects exact duplicate",()=>{const f=detectCannibalization({ref:"new",query:"wall thickness",problem:"how to determine wall thickness",entities:["injection molding"]},[{ref:"old",query:"wall thickness",problem:"how to determine wall thickness",entities:["injection molding"]}]);assert.equal(f[0].relation,"EXACT_DUPLICATE");});
test("market memory is fingerprinted and idempotent",()=>{const m=new InMemoryMarketMemory();const a=m.append({id:"e1",kind:"DECISION",subjectId:"d1",occurredAt:"2026-09-23T00:00:00.000Z",payload:{state:"RESEARCH_REQUIRED"}});const b=m.append({id:"e1",kind:"DECISION",subjectId:"d1",occurredAt:"2026-09-23T00:00:00.000Z",payload:{state:"RESEARCH_REQUIRED"}});assert.equal(a.fingerprint,b.fingerprint);assert.equal(m.all().length,1);});
