/** NEXMOLD V7.14 — source-preserving article producer. No hidden article-contract modules. */
import type { KnowledgeArticle } from "../data/knowledge.ts";
import type { RegionalPublishArtifact, V714ArticleContract, V714ArticleContentBlock } from "./types.ts";
export type V714ArticleSource = KnowledgeArticle;
export interface ProduceV714WhitePaperInput { readonly artifact: RegionalPublishArtifact; readonly sourceArticle: V714ArticleSource; readonly targetSlug: string; readonly sourceArticleSlug: string; readonly keyword?: string; readonly keywordCluster?: readonly string[]; }
function text(v: unknown): string { return typeof v === "string" ? v.replace(/\r\n?/g, "\n").trim() : ""; }
function block(v: unknown): V714ArticleContentBlock | null { if (typeof v === "string") { const c = text(v); return c ? { content: c, type: "source" } : null; } if (!v || typeof v !== "object") return null; const x = v as Record<string, unknown>; const c = text(x.content ?? x.body ?? x.text); if (!c) return null; const h = text(x.heading ?? x.title); return h ? { heading: h, content: c, type: text(x.type) || "source" } : { content: c, type: text(x.type) || "source" }; }
function sourceBlocks(source: KnowledgeArticle): V714ArticleContentBlock[] { const raw = (source as unknown as Record<string, unknown>).content; return Array.isArray(raw) ? raw.map(block).filter((x): x is V714ArticleContentBlock => Boolean(x)) : []; }
function assertArtifact(a: RegionalPublishArtifact): void { if (!a || a.seoEligibility.status !== "ELIGIBLE" || a.seoEligibility.applicability !== "APPLICABLE" || a.seoEligibility.compliance !== "VERIFIED" || a.evidence.completeness !== "COMPLETE" || !a.evidence.evidence.length || !a.evidence.semanticClaims.length) throw new Error("V714_ARTICLE_ARTIFACT_NOT_AUTHORIZED"); if (a.bindings.length !== a.evidence.semanticClaims.length) throw new Error("V714_ARTICLE_BINDING_CARDINALITY_MISMATCH"); }
export function produceV714WhitePaperV2(input: ProduceV714WhitePaperInput): V714ArticleContract { assertArtifact(input.artifact); if (!text(input.targetSlug) || !text(input.sourceArticleSlug) || input.targetSlug === input.sourceArticleSlug) throw new Error("V714_ARTICLE_TARGET_SOURCE_IDENTITY_INVALID"); const source = input.sourceArticle; const directAnswer = text((source as any).directAnswer) || text((source as any).description); if (!directAnswer) throw new Error("V714_ARTICLE_DIRECT_ANSWER_EMPTY"); const faq = Array.isArray((source as any).faq) ? (source as any).faq.map((f: any) => ({ question: text(f?.question), answer: text(f?.answer) })).filter((f: any) => f.question && f.answer) : []; const keywords = [...new Set([...(Array.isArray((source as any).seoKeywords) ? (source as any).seoKeywords : []).map(text), input.keyword ? text(input.keyword) : "", ...(input.keywordCluster ?? []).map(text)].filter(Boolean))]; return { schema: "nexmold.v7.14.article-contract.v2", articleId: input.artifact.pageId, title: text((source as any).title), slug: input.targetSlug, category: text((source as any).category), categorySlug: text((source as any).categorySlug), description: text((source as any).description), directAnswer, keyTakeaways: Array.isArray((source as any).keyTakeaways) ? (source as any).keyTakeaways.map(text).filter(Boolean) : [], content: sourceBlocks(source), faq, seoKeywords: keywords, lineage: { pageId: input.artifact.pageId, locale: input.artifact.locale, region: input.artifact.region, canonicalUrl: input.artifact.canonicalUrl, evidenceIds: input.artifact.evidence.evidence.map(e => String(e.id)), semanticClaimIds: input.artifact.evidence.semanticClaims.map(c => String(c.id)), sourceArtifactHash: input.artifact.pageContentHash }, sourceArtifact: input.artifact }; }
export function produceV714Article(artifact: RegionalPublishArtifact, source: V714ArticleSource, targetSlug?: string): V714ArticleContract { return produceV714WhitePaperV2({ artifact, sourceArticle: source, targetSlug: text(targetSlug) || `v714-${source.slug}`, sourceArticleSlug: source.slug }); }
export function isWhitePaperArticleV2(value: unknown): value is V714ArticleContract { if (!value || typeof value !== "object") return false; const x = value as Partial<V714ArticleContract>; return x.schema === "nexmold.v7.14.article-contract.v2" && typeof x.articleId === "string" && typeof x.slug === "string" && Array.isArray(x.content) && Boolean(x.sourceArtifact); }
