import { immutable, invariant } from "../../constitution/invariants.js";
import type { FoundationStore } from "../../foundation/types.js";
import type { PageFetcher, SearchProvider } from "../../acquisition/types.js";
import type { MarketDemand } from "./demand.js";
import { evaluateMarketDecision, type MarketDecisionEngineInput, type MarketDecisionEvidenceState, type MarketCoverageState } from "./decision-engine.js";
import { compileMarketResearchPlan } from "./research-strategy.js";
import { runMarketAcquisition, type MarketAcquisitionResult } from "./research-acquisition.js";
import { assessCoverage, type CoverageObservation } from "./coverage-intelligence.js";
import { detectEvidenceConflicts, type EvidenceStatement } from "./conflict-intelligence.js";
import { detectCannibalization, type CoverageIntent } from "./cannibalization-intelligence.js";
import { InMemoryMarketMemory, type MarketMemory } from "./market-memory.js";
export interface MarketOrchestratorInput { readonly decisionId:string; readonly demand:MarketDemand; readonly evidence:MarketDecisionEvidenceState; readonly coverage:MarketCoverageState; readonly coverageObservations?:readonly CoverageObservation[]; readonly evidenceStatements?:readonly EvidenceStatement[]; readonly coverageIntents?:readonly CoverageIntent[]; readonly searchProvider?:SearchProvider; readonly pageFetcher?:PageFetcher; readonly store?:FoundationStore; readonly actorId?:string; readonly memory?:MarketMemory; readonly occurredAt?:string; readonly signal?:AbortSignal; }
export interface MarketOrchestratorResult { readonly decision:ReturnType<typeof evaluateMarketDecision>["decision"]; readonly researchActions:ReturnType<typeof evaluateMarketDecision>["researchActions"]; readonly researchPlan:ReturnType<typeof compileMarketResearchPlan>|null; readonly acquisition:MarketAcquisitionResult|null; readonly coverage:ReturnType<typeof assessCoverage>; readonly conflicts:ReturnType<typeof detectEvidenceConflicts>; readonly cannibalization:readonly ReturnType<typeof detectCannibalization>[number][]; readonly memory:MarketMemory; }
export async function runMarketOrchestrator(input:MarketOrchestratorInput):Promise<MarketOrchestratorResult>{const memory=input.memory??new InMemoryMarketMemory();const coverageAssessment=assessCoverage(input.demand,input.coverageObservations??[]);const conflicts=detectEvidenceConflicts(input.evidenceStatements??[]);const engineInput:MarketDecisionEngineInput={decisionId:input.decisionId,demand:input.demand,evidence:{...input.evidence,contradictions:immutable([...input.evidence.contradictions,...conflicts.conflicts.map(x=>`${x.subject}:${x.predicate}`)])},coverage:{...input.coverage,equivalentCoverage:immutable([...input.coverage.equivalentCoverage,...coverageAssessment.equivalentRefs])},targetAsset:"ARTICLE"};const evaluated=evaluateMarketDecision(engineInput);let researchPlan=null;let acquisition=null;if(evaluated.decision.state==="RESEARCH_REQUIRED"){researchPlan=compileMarketResearchPlan(input.demand,evaluated.researchActions);invariant(input.searchProvider&&input.pageFetcher&&input.store,"V8_MARKET_ORCHESTRATOR_RESEARCH_ADAPTER_REQUIRED","Internet research execution requires SearchProvider, PageFetcher and FoundationStore.");acquisition=await runMarketAcquisition(researchPlan,input.searchProvider!,input.pageFetcher!,input.store!,{actorId:input.actorId,signal:input.signal});}memory.append({id:`memory:${input.decisionId}:decision`,kind:"DECISION",subjectId:input.demand.id,occurredAt:input.occurredAt??new Date().toISOString(),payload:{state:evaluated.decision.state,fingerprint:String(evaluated.decision.fingerprint)}});return immutable({decision:evaluated.decision,researchActions:evaluated.researchActions,researchPlan,acquisition,coverage:coverageAssessment,conflicts,cannibalization:input.coverageIntents&&input.coverageIntents.length?detectCannibalization({ref:input.demand.id,query:input.demand.queryObservations[0].normalizedQuery,problem:input.demand.problem,entities:input.demand.entities},input.coverageIntents):immutable([]),memory});}
