import type { FoundationStore } from "../../foundation/types.js";
import { ingestFetchedPage } from "../../acquisition/foundation-adapter.js";
import type { ExtractedEvidenceCandidate, FetchedPage, PageFetcher, SearchProvider } from "../../acquisition/types.js";
import { extractStructuredEvidence, extractTextEvidence } from "../../acquisition/source-extractor.js";
import { discoverCandidates, type DiscoveryInput } from "../web-discovery/discovery.js";
import type { DiscoveryBatch } from "../web-discovery/types.js";
import type { MarketResearchPlan } from "./research-strategy.js";
export interface MarketAcquisitionConfig { readonly actorId?:string; readonly maxCandidates?:number; readonly signal?:AbortSignal; }
export interface MarketAcquisitionRecord { readonly actionId:string; readonly candidateUrl:string; readonly page:FetchedPage; readonly acquisition:ReturnType<typeof ingestFetchedPage>; }
export interface MarketAcquisitionResult { readonly discovery:DiscoveryBatch; readonly acquisitions:readonly MarketAcquisitionRecord[]; readonly searchErrors:readonly {query:string;error:string}[]; readonly fetchErrors:readonly {url:string;error:string}[]; }
const msg=(e:unknown)=>e instanceof Error?e.message:String(e);
function evidenceKey(c:ExtractedEvidenceCandidate):string{return [c.locator,c.excerpt,c.section??"",c.parameter??"",c.value??"",c.unit??""].join("\u001f");}
function extract(page:FetchedPage):readonly ExtractedEvidenceCandidate[]{const all=[...extractStructuredEvidence(page.body),...extractTextEvidence(page.body,page.finalUrl)];const seen=new Set<string>();return all.filter(c=>{const k=evidenceKey(c);if(seen.has(k))return false;seen.add(k);return true;});}
export async function runMarketAcquisition(plan:MarketResearchPlan,searchProvider:SearchProvider,pageFetcher:PageFetcher,store:FoundationStore,config:MarketAcquisitionConfig={}):Promise<MarketAcquisitionResult>{const inputs:DiscoveryInput[]=[];const searchErrors:{query:string;error:string}[]=[];for(const item of plan.queries){if(config.signal?.aborted)throw new Error("V8_MARKET_RESEARCH_ABORTED");try{for(const r of await searchProvider.search(item.query,{signal:config.signal}))inputs.push({url:r.url,kind:"SERP_RESULT",title:r.title});}catch(e){searchErrors.push({query:item.query,error:msg(e)});}}const discovery=discoverCandidates(inputs);const acquisitions:MarketAcquisitionRecord[]=[];const fetchErrors:{url:string;error:string}[]=[];for(const c of discovery.candidates){if(acquisitions.length>=(config.maxCandidates??10))break;try{const page=await pageFetcher.fetch(c.url,{signal:config.signal});const acquisition=ingestFetchedPage(store,page,extract(page),{actorId:config.actorId});const actionId=plan.queries.find(q=>q.query&&c.url)?.actionId??plan.queries[0]?.actionId??"unknown";acquisitions.push({actionId,candidateUrl:c.url,page,acquisition});}catch(e){fetchErrors.push({url:c.url,error:msg(e)});}}return {discovery,acquisitions:immutable(acquisitions),searchErrors:immutable(searchErrors),fetchErrors:immutable(fetchErrors)};}
